apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-configmap
  labels:
    app: nginx-demo-config
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo-config
  template:
    metadata:
      labels:
        app: nginx-demo-config
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: website-content
        configMap:
          name: website-content