apiVersion: v1
kind: Pod
metadata:
  name: fehler-webseite
  labels:
    app: fehler-demo
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /nicht-existent
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5